# -*- coding: utf-8 -*-
"""CIE 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_kxziA-ksjehnHrDFMSKBHYZbewUlMX
"""

from sklearn.cluster import KMeans
import numpy as nm
import matplotlib.pyplot as plt
import pandas as pd
data = pd.read_csv('/content/Mall_Customers.csv')
data
data.head(5)

x = data.iloc[:, [3, 4]].values
x

wcss_list= []
for i in range(1, 11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state= 35)
  kmeans.fit(x)
  wcss_list.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss_list)
plt.title('The Elobw Method Graph')
plt.xlabel('Number of clusters')
plt.ylabel('wcss_list')
plt.show()

kmeans = KMeans(n_clusters=5, init='k-means++', random_state= 35)
y_predict= kmeans.fit_predict(x)
y_predict

plt.scatter(x[y_predict == 0, 0], x[y_predict == 0, 1], s = 100, c = 'blue',
label = 'Cluster 1')
plt.scatter(x[y_predict == 1, 0], x[y_predict == 1, 1], s = 100, c = 'green',
label = ' Cluster 2')
plt.scatter(x[y_predict== 2, 0], x[y_predict == 2, 1], s = 100, c = 'red',
label = 'Cluster 3')
plt.scatter(x[y_predict == 3, 0], x[y_predict == 3, 1], s = 100, c = 'cyan',
label = 'Cluster 4')
plt.scatter(x[y_predict == 4, 0], x[y_predict == 4, 1], s = 100, c ='magenta',
label = 'Cluster 5')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s = 300,
c = 'yellow', label = 'Centroid')
plt.title('Clusters of customers')
plt.xlabel('Annual Income ')
plt.ylabel('Spending Score ')
plt.legend()
plt.show()